replicaCount: 3

image:
  repository: myregistry.azurecr.io/my-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80

resources:
  limits:
    memory: "512Mi"
    cpu: "500m"
  requests:
    memory: "256Mi"
    cpu: "250m"

readinessProbe:
  path: /health/ready
  initialDelaySeconds: 5
  periodSeconds: 10

livenessProbe:
  path: /health/live
  initialDelaySeconds: 10
  periodSeconds: 15
